version: '2.4'

services:

  octo-klipper:
    image: octo-klipper
    container_name: octo-klipper
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
    environment:
      - ENABLE_MJPG_STREAMER=true
      - MJPG_STREAMER_INPUT="-n -r 1920x1080"
    devices:
      - "/dev/serial/by-id/usb-1a86_USB_Serial-if00-port0:/dev/ttyUSB0"
      - "/dev/video0:/dev/video0"
    volumes:
      - /home:/mount
    
  samba:
    image: dperson/samba
    container_name: samba
    restart: unless-stopped
    ports:
      - "139:139"
      - "445:445"
    volumes:
      - /home:/mount
    command: -n -s "home;/mount;yes;no;yes;all;all;all"
    privileged: true
  
  #  octoprint:
  #    image: octoprint/octoprint
  #    restart: unless-stopped
  #    ports:
  #      - 80:80
  #      - 8080:8080
  #    devices:
  #      - "/dev/serial/by-id/usb-1a86_USB_Serial-if00-port0:/dev/ttyUSB0"
  #    #  - "/dev/video1:/dev/video1"
  #      - "/dev/video0:/dev/video0"
  #    # use `python -m serial.tools.miniterm` to see what the name is of the printer
  #    #  - /dev/ttyACM0:/dev/ttyACM0
  #    #  - /dev/video0:/dev/video0
  #    volumes:
  #     - octoprint:/octoprint
  #    # uncomment the lines below to ensure camera streaming is enabled when
  #    # you add a video device
  #    environment:
  #      - ENABLE_MJPG_STREAMER=true
  #      - MJPG_STREAMER_INPUT="-n -r 1920x1080"
  #    #  - CAMERA_DEV=/dev/video1
  
  ####
  # uncomment if you wish to edit the configuration files of octoprint
  # refer to docs on configuration editing for more information
  ####

  #config-editor:
  #  image: linuxserver/code-server
  #  ports:
  #    - 8443:8443
  #  depends_on:
  #    - octoprint
  #  restart: unless-stopped
  #  environment:
  #    - PUID=0
  #    - GUID=0
  #    - TZ=America/Chicago
  #  volumes:
  #    - octoprint:/octoprint

volumes:
  octoprint:
